openapi: 3.0.0
info:
  title: Todo List API
  version: 1.0.0
  description: A simple API for managing a todo list, allowing users to create, read, update, and delete todo items.

servers:
  - url: http://localhost:8080

paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '201':
          description: The created todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /todos/{id}:
    get:
      summary: Get a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the todo item
      responses:
        '200':
          description: A single todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

    put:
      summary: Update a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: The updated todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

    delete:
      summary: Delete a todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the todo item
      responses:
        '200':
          description: Confirmation of deletion
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Todo deleted"
        '404':
          description: Todo not found

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the todo item
        task:
          type: string
          description: The task description
        completed:
          type: boolean
          description: Indicates whether the task is completed

    TodoInput:
      type: object
      properties:
        task:
          type: string
          description: The task description
        completed:
          type: boolean
          description: Indicates whether the task is completed
      required:
        - task
        - completed
